---
title: "Modern Data Structure HW04"
author: "Xueying Huang"
date: '2019-10-12'
output:
  html_notebook:
    toc: yes
  pdf_document:
    toc: yes
  word_document:
    toc: yes
  html_document:
    highlight: textmate
    theme: spacelab
    toc: yes
always_allow_html: yes
---
```{r}
devtools::install_github("tidyverse/dplyr")
library(dplyr)
content <- mget(ls("package:dplyr"), inherits = TRUE)
dplyr_functions <- Filter(is.function, content)


```
```{r}
library(purrr)
function_names <- names(dplyr_functions)
l <- array(nchar(function_names))
dimnames(l) <- list(function_names)
sort(l,decreasing = TRUE)[1]
```
```{r}
name <- names(dplyr_functions)
df_num_char <-data.frame(function_names, num_char = map_dbl(name, ~nchar(.x)))%>%
  arrange(desc(num_char))
df_num_char
```
```{r}
num_args <- map(dplyr_functions, formals) %>%
  map_dbl(length)%>%
  sort(decreasing = TRUE)
data.frame(num_args[1:10])
most_args <- num_args[1]
cat('"',names(most_args),'"', "has the most arguments !")
```
```{r}
a <-map(dplyr_functions, formals)
b <-unlist(unname(a))

df_args <- as.data.frame(matrix( data=NA, nrow = 1, ncol=1))
for (i in 1:length(b)){
  df_args <- rbind(df_args,names(b[i]))
}

table(df_args) %>% 
  as.data.frame() %>% 
  arrange(desc(Freq)) %>%
  head(5)
```
The most common argument is the ellipsis, or dot-dot-dot, argument. It allows people to simplify their code instead of explicitly naming and setting a default and passing it to the function.

```{r}
library(tidyverse)
library(tidyr)
library(dplyr)
library(WDI)
wdi_data <- WDI(indicator = c("NY.GDP.PCAP.PP.KD", "SP.DYN.IMRT.IN"), start = 1960, end = 2018, extra = TRUE)%>%
  filter(region != "Aggregates")%>%
  select(country, year, infmort = NY.GDP.PCAP.PP.KD, gdpcap = SP.DYN.IMRT.IN) 

wdi_tidy <- na.omit(wdi_data) %>%
  arrange(country)
wdi_tidy

```

```{r}
wdi_2018 <- subset(wdi_tidy, year == 2018) %>%
  arrange(desc(infmort))
wdi_2018
highest_infmort <- head(wdi_2018, 5)%>%
  arrange(desc(infmort))
lowest_infmort <-tail(wdi_2018,5)%>%
  arrange(infmort)
list_highest <- as.list(highest_infmort)
list_lowest <- as.list(lowest_infmort)
list_highest
list_lowest
```
```{r}
df = wdi_tidy
lm_fit <- lm(infmort ~ gdpcap, data=df)
ggplot(df, aes(x=gdpcap, y=infmort))+
  geom_point() +
  geom_line(data = fortify(lm_fit), aes(x = gdpcap, y = .fitted), color ='blue')+ labs(title=" PREDICTING INFANT MORTALITY FROM GDP PER CAPITA", x="GDP per capita", y="infant mortality")+ theme(plot.title = element_text(hjust = 0.5))


```
```{r}
wdi_region <- WDI(indicator = c("NY.GDP.PCAP.PP.KD", "SP.DYN.IMRT.IN"), start = 1960, end = 2018, extra = TRUE)%>%
  select(country, year, infmort = NY.GDP.PCAP.PP.KD, gdpcap = SP.DYN.IMRT.IN, region)%>%
  na.omit()
lm_region <- wdi_region %>% 
  split(wdi_region$region) %>%
  map(~ lm(infmort ~ gdpcap, data = .))

region_coef <- lm_region %>%
  map(~ coef(.)) %>%
  map_dbl("gdpcap")%>%
  sort()

region_coef_table <- data.frame(region_coef)
region_coef_table 

```

```{r}
lm_country <- wdi_tidy %>% 
  split(wdi_tidy$country) %>%
  map(~ lm(infmort ~ gdpcap, data = .))%>%
  map(summary)%>%
  map("coefficients") 

head(lm_country)

```

```{r}
lm_country_2 <- wdi_tidy %>%
  mutate(squared_gdpcap = gdpcap**2)

r1 <-lm_country_2 %>%
  split(lm_country_2$country) %>%
  map(~ lm(infmort ~ gdpcap, data = .))%>%
  map(summary)%>%
  map("adj.r.squared")

r2 <-lm_country_2 %>%
  split(lm_country_2$country) %>%
  map(~ lm(infmort ~ gdpcap + squared_gdpcap, data = .))%>%
  map(summary)%>%
  map("adj.r.squared")

x1<-data.frame(r1)
x2<-data.frame(r2)
full_join(x1, x2)
```
 I recommend to keep the squared term since the adjusted R squared has been improved.
